#!/bin/bash
# Distributed under the MIT license
# Copyright (c) 2015 Nicolae Ghimbovschi

WWWPATH="/opt/www"
INSTALL_ROOT="/usr/local/opt/info-service"
HTTPCONFPATH="${INSTALL_ROOT}/httpd.conf"
INDEXHTMLPATH="${INSTALL_ROOT}/index.html"
WEBSOCKETJSPATH="${INSTALL_ROOT}/websocketd.js"
WESOCKETD_INSTALL_PATH="${HOME}/Library/LaunchAgents/com.websocketd.plist"

function showActionMessage() {
	echo "⏳`tput setaf 12` $1 `tput op`"
}

function showMessage() {
	showActionMessage "$1"
	osascript -e "display notification \"$1\" with title \"Installer\""
}

function install() {
	showActionMessage "Installing Websocketd info service"

	cd "${INSTALL_ROOT}"
	npm install websocket
	cd ~-

	cat > "${WESOCKETD_INSTALL_PATH}" << EOF
	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
	   <key>Label</key>
	   <string>com.infoservice</string>
	   <key>Program</key>
	   <string>/usr/local/bin/node</string>
	   <key>ProgramArguments</key>
	   <array>
	        <string>/usr/local/bin/node</string>
	        <string>${WEBSOCKETJSPATH}</string>
	    </array>

	   <key>RunAtLoad</key>
	   <true/>
	   <key>KeepAlive</key>
	   <true/>
	   <key>StandardOutPath</key>
	   <string>/tmp/com.infoservice-agent.log</string>
	   <key>StandardErrorPath</key>
	   <string>/tmp/com.infoservice-agent_err.log</string>
	</dict>
	</plist>
	EOF
	launchctl load -w "${WESOCKETD_INSTALL_PATH}"

	showActionMessage "Setup and start Apache2"

	sudo mkdir -p "${WWWPATH}"
	sudo chown "$(whoami)" "${WWWPATH}"
	chmod a+rx "${WWWPATH}"
	umask 022 "${WWWPATH}"

	cp "${INDEXHTMLPATH}" "${WWWPATH}/index.html"
	sudo mv -f /etc/apache2/httpd.conf /etc/apache2/httpd.conf.original
	sudo cp "${HTTPCONFPATH}" /etc/apache2/httpd.conf
	sudo launchctl load -w /System/Library/LaunchDaemons/org.apache.httpd.plist
}

function uninstall() {
	rm -fr "${WWWPATH}"
	launchctl unload -w "${WESOCKETD_INSTALL_PATH}"
	sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist
	sudo mv -f /etc/apache2/httpd.conf.original /etc/apache2/httpd.conf
}
